### ISSUE TITLE
Add support for CentOS/RHEL 9 and derivatives

### ISSUE THREAD

**Issue by philipp-baumann** [Enchufa2/rspm#12]
```r
r$> rspm::enable()
Tracing function "install.packages" in package "utils"
Tracing function "update.packages" in package "utils"

r$> install.packages("terra")
Installing package into ‘/home/philipp/R/x86_64-pc-linux-gnu-library/4.2’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository https://packagemanager.rstudio.com/all/__linux__/centos9/latest/src/contrib:
  cannot open URL 'https://packagemanager.rstudio.com/all/__linux__/centos9/latest/src/contrib/PACKAGES'
Inspecting installed packages...
Warning message:
package ‘terra’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 

r$> sessioninfo::session_info()
─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.2 (2022-10-31)
 os       Rocky Linux 9.0 (Blue Onyx)
 system   x86_64, linux-gnu
 ui       X11
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       UTC
 date     2022-11-21
 pandoc   NA

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date (UTC) lib source
 cli           3.4.1   2022-09-23 [1] CRAN (R 4.2.2)
 rspm          0.2.2   2022-11-21 [1] Github (enchufa2/rspm@32abd91)
 sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.2.2)

 [1] /home/philipp/R/x86_64-pc-linux-gnu-library/4.2
 [2] /opt/R/4.2.2/lib/R/library

────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

```bash
[philipp@rocky9 ~]$ curl https://packagemanager.rstudio.com/all/__linux__/centos9/latest/src/contrib/PACKAGES
Distro identifier 'centos9' not supported
``

**Comment by philipp-baumann** [comment]
Seems like for Rocky 9 an easy approach would be to tweak `rspm::os()` minmally so that `"centos9"` is changed to `"rhel9"`. This is contributed on packagemanager.rstudio.com and since Rocky is binary compatible with RHEL this should work.

**Comment by Enchufa2** [comment]
Thanks, RHEL 9 wasn't available when I put together this package. They must have been providing this since recently. In fact, you can see that we don't claim to support CentOS 9 in the README yet.

I already sent v0.2.3 to CRAN, because this was a critical failure for CentOS 7 and 8 users, and I found that there were some problems for old versions of dpkg in Ubuntu too, so I'd like to bring it to CRAN as soon as possible. I'll prepare a PR for this, more camly, this weekend or the next. It should be easy, but I'd like to add a CentOS 9 machine to GitHub Actions for testing, and also test this manually in derivatives like Rocky and others. So I'll submit another version to CRAN in a few weeks when this is properly tested. I'll ping you when this is ready for testing if you have time.

**Comment by philipp-baumann** [comment]
Very nice! I feel all this work put in the package is really valuable for the broad R linux community. Happy that I have recently stumbled across it. Sure, happy to manually test this on Rocky 9. Once you feel it's ready, you can just ping me via GH.

**Comment by Enchufa2** [comment]
On CRAN now.
