### ISSUE TITLE
Is there a way to use rspm in a per-project environment using renv

### ISSUE THREAD

**Issue by wpdonders** [Enchufa2/rspm#4]
First of all, great work on the rspm package. I was wondering if there is a way to separate installed packages in a per-project way such as you do with `renv`. As far as I can tell, currently rspm installs packages system-wide; and it doesn't hook into the installation process when you call `renv::restore()`. Is there any way we can combine the per-project package separation offered by `renv` with the binary package installation offered by `rspm`?

**Comment by Enchufa2** [comment]
Note that {rspm} doesn't install packages system-wide. In fact, {rspm} doesn't install packages at all! This package does two things:

1) enables the RSPM repo, and
2) detects, installs and configures system requirements.

So it's not particularly tied to any installer or location, which means that, **yes, it's compatible with {renv}** or other approaches. Currently, we provide a hook to `install.packages`, so that (2) happens automatically. With {renv}, until we figure out a way to automate it, you can just run (2) manually and you'll be good to go.

This is not tested yet, but basically, you need three things to make this work:

1. Add {rspm} to your lockfile when you init a new project.
2. Add `rspm::enable()` to the `.Rprofile`, so that {renv} uses RSPM to install packages.
3. Run `rspm::install_sysreqs()` after every new package installation.

And you should be good to go. :) Eventually, it would be nice to figure out how to automate steps (2) and (3). Let me know how it goes if you try, and we could smooth things out if you find issues.

**Comment by Enchufa2** [comment]
See https://enchufa2.github.io/rspm/#renv-projects
