### ISSUE TITLE
Getting the system dependencies without installing the packages

### ISSUE THREAD

**Issue by statquant** [Enchufa2/rspm#6]
Hello,
thanks for this great package.
At work, where we use centos7, we have a policy to build our own rpms.
As such we have built a plan that, install some (800+) packages as a rpm. The challenge obviously is to derive which system dependencies needs to be installed. We do this by loading a system requirement file somewhere from the Rstudio website.
I assume you do the same thing (but better) in your package.
Would there be a way to get which dependencies are required from your package ?

Many thanks

**Comment by Enchufa2** [comment]
No, unfortunately you'll found no better way here, because that's not how we derive the required system dependencies. What we do here is to run `ldd` for every `.so` and examine the output for those libraries that are reported as "not found"; then, talk to the system package manager to figure out which packages provide them. So basically we rely on an existing precompiled binary and interrogate it to find out what's missing.

**Comment by statquant** [comment]
Maybe that's fine, when you say precompiled binary do you mean you ship the .so and then run ldd?
What would prevent you giving the result of the conversation with the package manager then?
That would be very useful, I could get only the missing rpm and add them as dependencies?

**Comment by Enchufa2** [comment]
Imagine we run `install.packages("units")`. This is what happens when {rspm} is enabled:

1. `utils::install.packages` installs the package, which is a binary one, because it comes from RStudio's RSPM.
2. {rspm} looks for `.so` files in `.libPaths()[1]` (which is the user library). The newly installed `<user_library_path>/units/libs/units.so` is found.
3. The output from `ldd` will look like this:

```bash
$ ldd <user_library_path>/units/libs/units.so 
        linux-vdso.so.1 (0x00007ffc32b2c000)
        libudunits2.so.0 => not found
        libR.so => /usr/lib64/R/lib/libR.so (0x00007fe8fe000000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fe8fdc00000)
        <etc.>
```

We just need to figure out how to install `libudunits2.so.0`. So, comparatively,

- {rspm} leverages the fact that precompiled binaries already have the info on what libraries were needed when they compiled them. So it just detects **only what's missing** for this particular user (maybe nothing) and provides it.
- From your description, you have the sources, and you need to figure out **all** the dependencies to build it.

**Comment by Enchufa2** [comment]
In other words, you have the same issue we have for other {bspm}-ready projects like cran2copr or r2u. This package is not helpful there.

**Comment by statquant** [comment]
My problem is actually simpler than what you describe because:
- we only have grosso modo a single build
As such I only need the dependencies I am missing. Sorry I did not mention it but I did not know where this conversation would go.
- we test our build plans in containers
So I could very well install everything and see what is missing after the fact, then add those dependencies.

I realize though that this is probably very peculiar and that it would not be useful to many people. Although once installed it could be cool to get a list of dependencies to be installed (even if vast majority of people will just want them installed and that's it).

Many thanks for taking the time to answer.
Have a nice day

**Comment by Enchufa2** [comment]
Then you just need to run `ldd` on all the `.so` and list all the missing dependencies like it is done here:

https://github.com/Enchufa2/rspm/blob/f85cbfcab250e9e34e24c707713581662d5c4843/R/manager.R#L12-L15

`rspm:::ldd_missing` returns a vector of missing libraries, such as `libudunits2.so.0` for the units example above. But there is no function in the package to convert that to actual packages, because yum and dnf are clever enough to figure it out for themselves.

**Comment by Enchufa2** [comment]
Ok, in 24ff353c7704dc0151175b8ceb99c3504ceb0c73 I made `ldd_missing` self-contained. I.e., you just need to run:

```r
> rspm:::ldd_missing()
[1] "libudunits2.so.0"
```

like so to get a list of missing libraries. Note that I'm not exporting that function, because it's unlikely anyone else needs it, and I don't want to complicate the API.

Then you can use yum to translate that into packages, e.g.:

```bash
$ yum whatprovides */libudunits2.so.0
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: ftp.cica.es
 * epel: mirrors.ptisp.pt
 * extras: ftp.cica.es
 * updates: ftp.cica.es
udunits2-2.2.20-2.el7.x86_64 : A library for manipulating units of physical quantities
Repo        : epel
Matched from:
Filename    : /usr/lib64/libudunits2.so.0
```

**Comment by statquant** [comment]
I'll do that.
Many thanks

**Comment by Enchufa2** [comment]
BTW, `ldd_missing` is quite simple. In Bash, it's a one-liner:

```bash
$ # find <user_library> -name *.so -exec ldd {} \; | grep "not found" | tr -d [:blank:] | cut -d"=" -f1
libudunits2.so.0
```

**Comment by statquant** [comment]
I agree, I did not think about checking ldd directly on all the package so but it makes sense.

**Comment by eddelbuettel** [comment]
Coming to this late but the idea of trying to fill the gaps left by `rspm` by checking `ldd` is not new: I played with that years ago when `rspm` appeared -- see https://github.com/eddelbuettel/chshli but didn't carry it forward so kudo to @enchufa for making it a service.

**Comment by Enchufa2** [comment]
Yes, thanks for the pointer, I didn't know about your project. Jeroen's package maketools has a similar functionality too, and this is how R-universe lists R package system dependencies. Also this is how autorequires have worked for years, at least in RPM builders. Very handy because as a packager most of the time you only need to list build-time requirements, and run-time requirements are inferred and added to the RPM automatically.
